version: "3.8"
services:
  tirmmrt:
    build:
      context: .
      dockerfile: ./TIR_MMRT/Dockerfile
    networks:
      thesis:
        ipv4_address: 172.28.0.5
  tcpclient:
    build:
      context: .
      dockerfile: ./TCPClient/Dockerfile
    networks:
      thesis:
        ipv4_address: 172.28.0.4
  udpclient:
    build:
      context: .
      dockerfile: ./UDPClient/Dockerfile
    networks:
      thesis:
        ipv4_address: 172.28.0.3
networks:
  thesis:
    ipam:
      driver: default
      config:
          - subnet: 172.28.0.0/16
